#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging
readonly LIBDIR="${HOME}/.local/lib/pacmd-shorthands"

"${LIBDIR}/get-source-input" "analog" | xargs --no-run-if-empty -I @ pactl set-source-port @ analog-input-rear-mic

exit $?
