#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging

test "$#" -eq 0 && {
    printf "Input a word about a sink-input:? "
    read -r REPLY
}

pacmd-get-sink-input "${1:-$REPLY}" | xargs --no-run-if-empty pacmd-bluez-sink move-sink-input

exit $?
