#!/bin/sh
set -Ceu
#set -x ## Uncomment for debugging

test "x${1:-}" = "x" && {
    printf "Input a word about a sink-input:? "
    read -r REPLY
}

pactl list sink-inputs | sed --expression="/${1:-$REPLY}/g; /^[0-9]\+$/q; s/^Sink [^0-9]\+\(.\+\)/\1/; /^[0-9]\+$/h; d"

exit $?
