#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging
readonly LIBDIR="${HOME}/.local/lib/pacmd-shorthands"

test "$#" -eq 0 && {
    printf "Input a word about a sink-input:? "
    read -r REPLY
}

"${LIBDIR}/get-sink-input" "${1:-$REPLY}" | xargs --no-run-if-empty pacmd-bluez-sink move-sink-input

exit $?
