#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging

LC_ALL=C pactl list short sinks | sed --expression="/analog/{; s/.\+[[:space:]]\([^[:space:]]\+analog[^[:space:]]\+\).\+/\1/; p; }; d"

exit $?

