#!/bin/bash
set -Cu
#set -vx ## Uncomment for debugging
readonly LIBDIR="${HOME}/.local/lib/pacmd-shorthands"

mapfile -t < <("${LIBDIR}/get-sink-input" "${1:-}")

if [[ "${#MAPFILE[@]}" -gt 0 ]]; then
    for line in "${MAPFILE[@]}"
    do
        pacmd-analog-sink move-sink-input "$line"
    done
fi

exit $?
