#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging

LC_ALL=C pactl list short sources | sed "/analog-stereo$/{; s/.\+[[:space:]]\([^[:space:]]\+analog-stereo\)[[:space:]].\+/\1/; p; }; d"

exit $?
