#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging

LC_ALL=C pactl list short sinks | sed --expression="/bluez_sink/{; s/.\+[[:space:]]\([^[:space:]]\+bluez[^[:space:]]\+\).\+/\1/; p; }; d"

exit $?
