#!/bin/sh
## Control Pulse Audio
set -Cu
#set -vx ## Uncomment for debugging

test $# -eq 0 || {
    case "$1" in
        mute)
            pactl list short sink-inputs | cut --fields=1 | xargs -I @ pactl set-sink-input-mute @ toggle
            ;;
        *)
            pacmd-get-default-sink | xargs --no-run-if-empty -I @ pactl set-sink-volume @ "$1" && \
            paplay "${XDG_DATA_HOME}/sounds/default/stereo/audio-volume-change.oga"
            ;;
    esac

    printf "Current Volume: %s\n" "$(LANG=C pactl list sinks | sed --expression="/Volume:/{; s#^[^/]\+/[[:space:]]\+\([^[:space:]]\+\).\+#\1#; q; }; d")" 1>&2
}

exit $?
