#!/bin/bash
## Control Pulse Audio
set -Cu
#set -vx ## Uncomment for debugging
readonly LIBDIR="${HOME}/.local/lib/pacmd-shorthands"

test $# -eq 0 || {
    case "$1" in
        mute)
            pactl list short sink-inputs | cut --fields=1 | xargs -I @ pactl set-sink-input-mute @ toggle
            ;;
        *)
            if [[ "${2:-}" == "all" ]]; then
                mapfile -t < <(pactl list short sinks | cut --fields=2)
                for line in "${MAPFILE[@]}"
                do
                    pactl set-sink-volume "$line" "$1"
                done
            else
                "${LIBDIR}/get-default-sink" | xargs --no-run-if-empty -I @ pactl set-sink-volume @ "$1"
            fi
            paplay "${XDG_DATA_HOME}/sounds/default/stereo/audio-volume-change.oga"
            ;;
        esac

    printf "Current Volume: %s\n" "$(LANG=C pactl list sinks | sed "/Volume:/{; s@^[^/]\+/[[:space:]]\+\([^[:space:]]\+\).\+@\1@; q; }; d")" 1>&2
}

exit $?
