#!/bin/sh
## Control Pulse Audio
set -Cu
#set -vx ## Uncomment for debugging

test $# -eq 0 || {
    case "$1" in
        mute)
            pactl list short sink-inputs | cut --fields=1 | xargs -I{} pactl set-sink-input-mute {} toggle
            ;;
        *) pacmd-get-default-sink | xargs --no-run-if-empty -I{} pactl set-sink-volume {} "$1" ;;
    esac

    canberra-gtk-play --id="audio-volume-change"
    printf "Current Volume: %s\n" "$(pactl list sinks | sed --expression="/Volume:/q; d" | cut -d'/' --fields=2 | tr --delete " ")" 1>&2
}

exit $?
