#!/bin/sh
set -Cu
#set -vx ## Uncomment for debugging

test "$#" -eq 0 && {
    printf "Input a word about a sink-input:? "
    read -r REPLY
}

LC_ALL=C pactl list sink-inputs | sed "/${1:-$REPLY}/g; /^[0-9]\+$/q; s/^Sink [^0-9]\+\(.\+\)/\1/; /^[0-9]\+$/h; d"

exit $?
