#!/bin/bash
set -Cu
#set -vx ## Uncomment for debugging
mapfile -t < <(LC_ALL=C pactl list sink-inputs | sed "s/^[[:space:]]//; /library\./d; /Sink Input/p; /\.binary/p; /\.name/p; d")

if [[ "$#" -eq 0 ]]; then
    echo "Select sink-input index..." >&2
    for line in "${MAPFILE[@]}"
    do
        echo "$line"
    done
    mapfile -t < <(LC_ALL=C pactl list short sink-inputs | cut --field=1)
    select line in "${MAPFILE[@]}"
    do
        echo "$line"
        break
    done
else
    for line in "${MAPFILE[@]}"
    do
        if [[ "${line#Sink Input #}" =~ ^[[:digit:]]+$ ]]; then
            sinkinput="${line#Sink Input #}"
        elif [[ "$line" =~ $1 ]]; then
            echo "$sinkinput"
            break
        fi
    done
fi

exit $?
